apps/usuario/urls.py
from django.conf.urls import url

from apps.usuario.views import RegistroUsuario, perfilusuario

urlpatterns = [
    url(r'^registrar/$', RegistroUsuario.as_view(), name='registrar'),
    url(r'^perfil/$', perfilusuario, name='perfil'),
]

apps/web/urls.py
from django.conf.urls import url, include
from .views import index, SearchView

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^search/', SearchView.as_view(), name="search"),

]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    # Apps internas
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.web.urls', namespace="web")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^comercio/', include('apps.comercio.urls', namespace="comercio")),

    # Apps externas
    # Auth URLS
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^comments/', include('django_comments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/web/index/buscador.html
{% load staticfiles %}

    <!-- Buscador -->
    <div class="row">
    <div class="col s12 m12 l12" id="banner_inicio">
        <div class="row container">
            <div class="row">
                <div class="col s12 m12 l12" style="background-color:rgba(0,0,0,0.64);margin-top:10px;border-radius:25px;">
                    <em>
                        <span class="center grey-text text-lighten-2">
                            <h5> Encontra lo que queres y donde queres comer! </h5>
                        </span>
                    </em>
                </div>
            </div>

            <!-- Mapa Comercios -->
            <div class="row">
                <div class="col s12 center" id="map" style="height:50%;border-radius:25px;"></div>

                <script>
                    function initMap() {
                          var map = new google.maps.Map(document.getElementById('map'), {
                            zoom: 14,
                            center: {lat: -28.469235, lng: -65.778826},
                            disableDefaultUI: true
                          });

                        {% if domicilios %}
                            {% for domicilio in domicilios %}
                                    var marker1 = new google.maps.Marker({
                                        position: new google.maps.LatLng({{ domicilio.position }}),
                                        map: map,
                                    });

                                    var infowindow = new google.maps.InfoWindow({
                                        content: '<a href="{% url 'comercio:perfil' domicilio.comercio.codigo %}"> Hola {{ comercio.nombre }}</a>',
                                      });

                                    marker1.addListener('click', function() {
                                        infowindow.open(map, marker1);
                                    });
                            {% endfor %}
                        {% endif %}
                    }
                </script>
                <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHpVXm1_SpgpAUOMwQ-c9PC-dtnklO3n0&callback=initMap" async defer></script>
            </div>

            <div class="row z-depth-3" style="background-color:rgba(0, 0, 0, 0.8);border-radius: 25px;">
                <form action="{% url 'web:search' %}" method="GET" class="col s12 m12 l12">
                    {% csrf_token %}
                    <div class="row">

                        <div class="input-field col s12 m4 l4">
                            <input name="q1" id="search-food" type="search" placeholder="Comida">
                            <label for="search-food" id="ico_search1"><i class="material-icons">search</i></label>
                            <i class="material-icons" id="ico_close1">close</i>
                        </div>

                        <div class="input-field col s12 m4 l4">
                            <input name="q2" id="search-commerce" type="search" placeholder="Comercio">
                            <label for="search-commerce" id="ico_search2"><i class="material-icons">search</i></label>
                            <i class="material-icons" id="ico_close2">close</i>
                        </div>

                        <div class="input-field col s12 m4 l4">
                            <input name="q3" id="search-adress" type="search" placeholder="Direccion">
                            <label for="search-adress" id="ico_search3"><i class="material-icons">search</i></label>
                            <i class="material-icons" id="ico_close3">close</i>
                        </div>

                    </div>

                    <div class="row">
                        <div class="col s6 m8 l8 center">
                            <input name="q4" type="checkbox" class="filled-in" id="filled-in-box" checked="checked" />
                            <label for="filled-in-box" style="left:20px;">Buscar a partir de mi ubicacion</label>
                        </div>

                        <div class="col s6 m4 l4 right">
                            <button class="btn waves-effect green darken-4" type="submit" name="action">Buscar
                                <i class="material-icons right">send</i>
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>

    <!-- Funcionalidad -->
	<div class="row brown darken-2" style="padding-bottom:30px;">

		<div class="col s3 m3 l3 offset-s1 offset-m1 offset-l1 center">
            <div class="promo">
                <img src="{% static 'img/icons/search.png' %}" width="25%" style="margin-top:30px;">
                <h5><p class="promo-caption white-text">Busca</p></h5>
                <p class="light center white-text">Realiza tu busqueda indicando lo que deseas comer, puedes filtrar
                    los resultados añadiendo el nombre del comercio, o tu direccion. Tambien puedes buscar a partir de
                    tu ubicacion de GPS</p>
            </div>
		</div>

		<div class="col s3 m3 l3 center">
            <div class="promo">
			    <img src="{% static 'img/icons/commerce.png' %}" width="25%" style="margin-top:30px;">
                <h5><p class="promo-caption white-text">Elije un comercio</p></h5>
                <p class="light center white-text">Informacion detallada del comercio</p>
            </div>
		</div>

		<div class="col s3 m3 l3 center">
            <div class="promo">
			    <img src="{% static 'img/icons/star.png' %}" width="25%" style="margin-top:30px;">
                <h5><p class="promo-caption white-text ">Califica</p></h5>
                <span class="light center white-text">Califica a los comercios, y realiza comentarios de los mismos</span>
            </div>
		</div>

	</div>

    </div>