apps/comercio/urls.py
from django.conf.urls import url
from .views import Perfil, MiNegocio, Productos, ListaComercio, DetalleComercio, FormularioRegistroComercio


urlpatterns = [

    url(r'^lista/$', ListaComercio.as_view(), name='lista'),
    url(r'^detalle/(?P<pk>\d+)/$', DetalleComercio.as_view(), name='detalle'),
    url(r'^perfil/(?P<pk>\d+)/$', Perfil.as_view(), name='perfil'),
    url(r'^minegocio/(?P<pk>\d+)/$', MiNegocio.as_view(), name='minegocio'),
    url(r'^minegocio/(?P<pk>\d+)/productos/$', Productos.as_view(), name='productos'),
    url(r'^registroComercio/$', FormularioRegistroComercio.as_view())
]

apps/web/urls.py
from django.conf.urls import url, include
from .views import index, SearchView

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^search/', SearchView.as_view(), name="search"),

]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [

    # Apps internas
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.web.urls', namespace="web")),
    url(r'^usuario/', include('apps.usuario.urls', namespace="usuario")),
    url(r'^comercio/', include('apps.comercio.urls', namespace="comercio")),

    # Apps externas
    # Auth URLS
    url(r'^accounts/', include('allauth.urls')),
    url(r'^ratings/', include('star_ratings.urls', namespace='ratings', app_name='ratings')),
    url(r'^comments/', include('django_comments.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Lista.html
{% extends 'base.html' %}


{% block content %}
    <div class="section white">
        <div class="row container">
             <div class="col s12 m12">

                <script>
                // Note: This example requires that you consent to location sharing when
                // prompted by your browser. If you see the error "The Geolocation service
                // failed.", it means you probably did not give permission for the browser to
                // locate you.

                function initMap() {
                  var map = new google.maps.Map(document.getElementById('map'), {
                    center: {lat: -34.397, lng: 150.644},
                    zoom: 16
                  });
                {% if object_list %}
                {% for comercio in object_list %}
                  var myLatLng = {lat: {{ comercio.latitud }}, lng: {{ comercio.longitud }}};
                  var marker = new google.maps.Marker({
                    position: myLatLng,
                    map: map,
                    title: '{{ comercio.nombre }}'
                  });
                {% endfor %}
                  var infoWindow = new google.maps.InfoWindow({map: map});

                  // Try HTML5 geolocation.
                  if (navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(function(position) {
                      var pos = {
                        lat: position.coords.latitude,
                        lng: position.coords.longitude
                      };

                      infoWindow.setPosition(pos);
                      infoWindow.setContent(' Usted esta Aqui');
                      map.setCenter(pos);
                    }, function() {
                      handleLocationError(true, infoWindow, map.getCenter());
                    });
                  } else {
                    // Browser doesn't support Geolocation
                    handleLocationError(false, infoWindow, map.getCenter());
                  }
                }

                function handleLocationError(browserHasGeolocation, infoWindow, pos) {
                  infoWindow.setPosition(pos);
                  infoWindow.setContent(browserHasGeolocation ?
                                        'Error: The Geolocation service failed.' :
                                        'Error: Your browser doesn\'t support geolocation.');
                }

                </script>
                    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBHpVXm1_SpgpAUOMwQ-c9PC-dtnklO3n0&signed_in=true&callback=initMap" async defer>
                </script>


                <h2 class="header">Resultado de Busqueda</h2>
                <div id="map" style="width: 100%; height: 400px;"></div>


                {% for comercio in object_list %}
                 <div class="row card horizontal">
                      <div class="col s3">
                          <div class="card-image">
                            <img src="{{ comercio.imagen.url }}">
                          </div>
                      </div>
                        <div class="col s9">
                          <div class="card-stacked">
                            <div class="card-content">
                                <a href="{% url 'comercio:detalle' comercio.pk %}"><h3>{{ comercio.nombre }}</h3></a>
                                <p>{{ comercio.rubro }}</p>
                                <p>{{ comercio.horarios }}</p>
                                <p>{{ comercio.domicilio }}</p>
                                <p>{{ comercio.direccion }}</p>
                            </div>
                          </div>
                        </div>
                 </div>

                 {% endfor %}
                 {% else %}
                    <h1>No se encontraron de Comercios</h1>
                 {% endif %}
             </div>
        </div>
    </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load static %}
{% load account %}
{% load socialaccount %}
{% providers_media_js %}

<!DOCTYPE HTML>
<html lang="es">
    <head>
        <meta charset="UTF-8">
        {% block css %}
            <link rel="stylesheet" href="{% static 'css/styles.css' %}">
            <link rel="stylesheet" href="{% static 'css/jquery.dataTables.min.css' %}">
            <link rel="stylesheet" href="http://fonts.googleapis.com/icon?family=Material+Icons">
            <link rel="stylesheet" href="{% static 'css/materialize.css' %}">
            <link rel="stylesheet" href="https://unpkg.com/leaflet@1.0.1/dist/leaflet.css"/>

        {% endblock %}

        <title>{% block title %} Document {% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
    </head>



    <body class="brown lighten-4">

        <!-- NAVBAR -->
        <div class="navbar-fixed">
            {% include 'navbar.html' %}
        </div>

        <!--CONTENIDO-->
        <div class="row">
            {% block content %}

            {% endblock %}
        </div>

        <!-- FOOTER -->
        <div class="row">
	        {% include 'footer.html' %}
        </div>

        {% block javascript %}
            <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
            <script language="JavaScript" src="{% static 'js/script.js' %}"></script>
            <script src="{% static 'js/materialize.js' %}"></script>
            <script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
            <script src="https://unpkg.com/leaflet@1.0.1/dist/leaflet.js"></script>
            <script language="JavaScript">
                $(document).ready(function(){
                    $('ul.tabs').tabs();
                });
            </script>
        {% endblock %}

    </body>

</html>

templates/footer.html
{% load staticfiles %}
<footer class="page-footer brown darken-1">
	    <div class="row">
		    <div class="col l2 s3 center">
			    <img src="{% static 'img/img_project/Logo.png' %}" width="90%"/>
				<br><h6 class="white-text">Redes Sociales</h6><br>
				    <a href="#"><img src="{% static 'img/social/facebook.png' %}" width="20%" alt="Facebook"></a>
				    <a href="#"><img src="{% static 'img/social/google.png' %}" width="20%" alt="Google+"></a>
				    <a href="#"><img src="{% static 'img/social/twitter.png' %}" width="20%" alt="Twitter"></a>
			</div>
	    </div>

        <div class="footer-copyright">
            <div class="container">
                Team HidraSoft
                <a class="grey-text text-lighten-4 right" href="#!">More Links</a>
            </div>
        </div>
</footer>

templates/navbar.html
{% load staticfiles %}
{% load account %}
{% load socialaccount %}

<!-- Dropdown Usuario -->
<ul id="dropdown-usuario" class="dropdown-content brown lighten-2">
    <li><a href="/usuario/perfil/" class="white-text">Mi Perfil</a></li>
    <!-- Aca hay que hacer un if si es que el usuario es admin de comercio -->
    <li><a href="/comercio/perfil/1" class="white-text">Mi Negocio</a></li>
    <!-- Fin If -->
    <li><a href="/accounts/logout/" class="pull-right white-text">Cerrar Sesion</a></li>
</ul>

<nav class="brown">
	<div class="nav_wrapper">
		<a href="{% url 'web:index' %} ">
			<img src="{% static 'img/img_project/Logo.png' %}" style="width: 150px; height:60px;">
		</a>

		<a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
		<ul id="nav-mobile" class="right hide-on-med-and-down">
            {% if request.user.is_authenticated %}

                {% if request.user.first_name or request.user.last_name %}
                    <div class="row">
                        <div class="col s1 offset-s8">
                            <li><img class="circle responsive-img" src="{{ user.socialaccount_set.all.0.get_avatar_url }}" style="width:100%;margin-top:10%;"/>
                        </div>

                        <div class="col s3">
                            <a class="dropdown-button" data-beloworigin=true data-activates="dropdown-usuario"><i class="material-icons right">arrow_drop_down</i>{{ request.user.first_name }} {{ request.user.last_name }}</a></li>
                        </div>
                    </div>
                {% else %}
                    <i class="material-icons left">person</i>
                    <li><a class="dropdown-button" data-beloworigin=true data-activates="dropdown-usuario"><i class="material-icons right">arrow_drop_down</i>{{ request.user.username }}</a></li>
                {% endif %}

			{% else %}

				<li><a class="waves-effect waves-teal pull-right" href="/accounts/login/"><i class="material-icons left">vpn_key</i>Iniciar Sesion</a></li>

			{% endif %}

        </ul>

		<ul class="side-nav" id="mobile-demo">
			<li><a href="">Registrarse</a></li>
			<li><a href="">Iniciar Sesion</a></li>
		</ul>
	</div>
</nav>

<script>
     $('.dropdown-button').dropdown({
      inDuration: 300,
      outDuration: 225,
      constrain_width: false, // Does not change width of dropdown to that of the activator
      hover: true, // Activate on hover
      gutter: ($('.dropdown-content').width()*3)/2.5 + 5, // Spacing from edge
      belowOrigin: true, // Displays dropdown below the button
      alignment: 'left' // Displays dropdown with edge aligned to the left of button
    }
  );

</script>